version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bdtuto
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: "npm start --host 0.0.0.0"
    depends_on:
      - postgres

volumes:
  postgres-data: